### ISSUE TITLE
No date and bo3 problem at the 'results'

### ISSUE THREAD

**Issue by TomHaupt** [dajk/hltv-api#23]
Hi,

First of all, I´m very grateful that you´ve included a dedicated API for this scraper.

But I´ve got a problem with the "results".
The Json doesn´t include the date when the match took place
and the maps and scores for bo3´s are only: 

maps: "bo3"
team1 result: 2
team2 result: 1

would it be possible to make 3 single entrys for every map?
or to include the maps and results like a csv? like:

maps: "inf,mrg,ovp"
team1 result: 8,16,16
team2 result: 16,7,9

I would edit the files myself to get the result the way I want 🌝 
but I´m not sure of what files to edit.

Thanks.

**Comment by dajk** [comment]
Hi @TomHaupt 

Thanks for the issue, it's been a while since I added features, but I absolutely understand your requirements and I'd be more then happy to support that for you.

- [ ] I will check the markup structure on HLTV and see if it's doable
- [ ] Choose the API structure, either comma/pipe separated or having an array of matches
