### ISSUE TITLE
HLTV has Change.

### ISSUE THREAD

**Issue by Alfrad** [dajk/hltv-api#4]
http://www.hltv.org/news.rss.php
http://www.hltv.org/blog.rss.php
http://www.hltv.org/demo.rss.php

They don't work anymore, is it possible to fix?

**Comment by dajk** [comment]
Welcome @Alfrad. It's nice to see that someone has been playing with this piece of code. I noticed the new HLTV, I'll take a look to it asap...

**Comment by Friss** [comment]
Looking at the forums they said they were going to take a look at RSS this week. Pretty upsetting that they would launch the new design without RSS.

**Comment by dajk** [comment]
Yes, accepted by Nomad: [link](https://www.hltv.org/news/20530/a-new-beginning-for-hltvorg#r21524799)

I'll, however, create a scraper for the data we can reach if it takes some more time.

**Comment by Alfrad** [comment]
@dajk ' - I'll get a new rss link made soon ' mens, ' - It will not work anymore, okay? ' hehe.

**Comment by ItsCEED** [comment]
@dajk well, there are many ppl looking at this code and i bet on it, im one of them. Scraping directly could cause ban and issues like that. Just letting you know :D

**Comment by dajk** [comment]
@ItsCEED Yes, that's true and the reason why I created this library using these RSS links rather than directly scraping data. We have an access just for few things though, not the most interesting like match overview, statistics, topics... So any idea about improving the module would be very welcome. I should also write some contribution docs, so everyone can participate easily.

Thanks anyways for such a nice words, I'm glad you found this useful.

**Comment by ItsCEED** [comment]
@dajk Best solution i guess is start scraping GG? (gosu gamers) they even have more games to scrape and the site structure from game to game is not really different will be something like 1 hit 2 flys

**Comment by dajk** [comment]
@ItsCEED To be honest, I was considering this option some time ago, but I found HLTV unique and very passionate to this game. I'll rather stick with HLTV (at least for this module), since the name has the same meaning :)

**Comment by ItsCEED** [comment]
@dajk Thats true, They are best at what they are doing, not sure but i guess they are keeping stats back from 1,6 till now. But, if you really want to provide a solution close to this one Gosu is the way to go, plus with many more games than just CS.

Imma be the first guy to run a website based on your module incase you decide to make it :P

**Comment by dajk** [comment]
@ItsCEED Hah, nice to hear that. Maybe I'll consider creating a specific module for this purpose and scraping data around, depending of what we need. 
For Gosugamers though check [this module](https://github.com/rannmann/node-gosugamers-api). Maybe just create some PR and fix since it's not updated some time, might be something out of date. Ofc, if the guy is still maintaining this.

**Comment by dajk** [comment]
If somebody has missed, there is a new rss link but just for news: https://www.hltv.org/rss/news
